version: "3.7"
volumes:
  mongodb-data:
    name: mongodb-data
networks:
  sw-stack:
    driver: bridge

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
        - sw-stack 
  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    restart: unless-stopped
    networks:
      - sw-stack
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    volumes:
      - mongodb-data:/data/db
    depends_on:
      - mongodb
    ports:
      - 8081:8081

  spider_1:
    image: seanhong2000/app
    build: .
    command: bash -c "cd stackspider && scrapy crawl programmersbot"
    volumes:
      - .:/backend
    depends_on: 
      - mongodb
    networks:
      - sw-stack

  spider_2:
    image: seanhong2000/app
    build: .
    command: bash -c "cd stackspider && scrapy crawl jumpitbot"
    volumes:
      - .:/backend
    depends_on: 
      - mongodb
    networks:
      - sw-stack
  
  spider_3:
    image: app
    build: .
    command: bash -c "cd stackspider && scrapy crawl kiwizzlebot"
    volumes:
      - .:/backend
    depends_on: 
      - mongodb
    networks:
      - sw-stack
  

  web:
    image: seanhong2000/app
    build: .
    command: bash -c "cd backend && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/backend
    environment:
      MONGOHOST: mongodb
      MONGODB: stackdb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      USERNAME: root
      PASSWORD: example
    ports:
      - "8000:8000"
    expose: 
      - "8000"
    depends_on:
      - mongodb
    networks:
      - sw-stack
    # deploy:
    #   replicas: 3
    #   resources:
    #     limits:
    #       cpus: '0.001'
    #       memory: 50M
